# Makefile.common - shared code between MesaLib ports.
#
# !!! Here be dragons !!! (they seem to be everywhere these days)
#
# Remember to upgrade the following ports everytime you bump MESAVERSION:
#
#    - graphics/mesa-dri
#    - graphics/mesa-libs

MESAVERSION=	26.2.2

MASTER_SITES=	https://mesa.freedesktop.org/archive/

DISTFILES=	mesa-${MESAVERSION}${EXTRACT_SUFX}

MAINTAINER=	x11@FreeBSD.org

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/docs/license.rst

COMPONENT=	${PORTNAME:tl:C/^lib//:C/mesa-//}

BUILD_DEPENDS+=	${PYTHON_PKGNAMEPREFIX}mako>0:textproc/py-mako@${PY_FLAVOR} \
		${PYTHON_PKGNAMEPREFIX}packaging>0:devel/py-packaging@${PY_FLAVOR} \
		${PYTHON_PKGNAMEPREFIX}pyyaml>0:devel/py-pyyaml@${PY_FLAVOR}

LIB_DEPENDS+=	libdrm.so:graphics/libdrm \
		libexpat.so:textproc/expat2

USES+=		compiler:c++11-lib bison meson pathfix pkgconfig \
		python:build shebangfix tar:xz

.if ${PORT_OPTIONS:MX11}
USES+=	xorg
.endif

# only have one port to check with portscout.
.if ${PORTNAME} != mesa-dri
PORTSCOUT=	ignore:1
.endif

MASTERDIR=	${.CURDIR:H:H}/graphics/mesa-dri
PATCHDIR=	${MASTERDIR}/files
WRKSRC=		${WRKDIR}/mesa-${MESAVERSION}
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist
PKGHELP=	${.CURDIR}/pkg-help
PKGINSTALL=	${.CURDIR}/pkg-install
PKGDEINSTALL=	${.CURDIR}/pkg-deinstall

LTO_UNSAFE=	Upstream recommends against LTO https://gitlab.freedesktop.org/mesa/mesa/-/commit/cb571550cc63f6bb22e0212dc681d8a2cd90926c

.include <bsd.port.pre.mk>

BINARY_ALIAS+=	python3=${PYTHON_VERSION}

CONFIGURE_ENV+=	LLVM_CONFIG=${LLVM_CONFIG}
# Needed to locate libclc
CONFIGURE_ENV+=	PKG_CONFIG_PATH="${LLVM_PREFIX}/libdata/pkgconfig"

# Some symbols in mesa's linker version scripts are not always defined,
# depending on configuration options. Suppress errors with lld >= 17 due to
# these undefined symbols.
LDFLAGS+=	-Wl,--undefined-version

LDFLAGS+=	-Wl,-rpath=${LOCALBASE}/llvm${LLVM_VERSION}/lib
MESON_ARGS+=	-Dllvm=enabled \
		-Dlibunwind=disabled \
		-Dgallium-mediafoundation=disabled

# Enable all video codecs so RADV/ANV expose the full set of Vulkan Video
# decode/encode extensions (H.264, H.265, AV1) and the gallium VA-API path
# gets them too. Upstream default is 'all_free', which strips
# patent-encumbered codecs.
MESON_ARGS+=	-Dvideo-codecs=all

post-patch:
	# Disable some autostaff.
	@${REINPLACE_CMD} -e 's|dep_elf = dependency.*|dep_elf = null_dep|g' \
		-e 's|dep_libudev =.*|dep_libudev = null_dep|g' \
		-e 's|dep_openmp =.*|dep_openmp = null_dep|g' \
		-e 's|dep_xcb_keysyms =.*|dep_xcb_keysyms = null_dep|g' \
		${WRKSRC}/meson.build
	# Force use libelf headers from base.
	# gelf.h includes <libelf.h> so remove it to avoid conflict between
	# </usr/include/libelf.h> and <libelf.h>=/usr/local/include/libelf.h.
	${REINPLACE_CMD} -e 's|#include <gelf.h>||g' \
		-e 's|#include <libelf.h>|#include </usr/include/libelf.h>|g' \
		${WRKSRC}/src/amd/common/ac_rtld.c \
		${WRKSRC}/src/amd/common/ac_rgp_elf_object_pack.c
